### ISSUE TITLE
iOS/macOS linear capture too dark and CaptureFromScreen issue

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProMovieCapture#29]
According to these posts there are issues with capturing when using floating point texture and linear space on iOS/macOS:
https://forum.unity.com/threads/released-avpro-movie-capture.120717/reply?quote=5091506
https://forum.unity.com/threads/released-avpro-movie-capture.120717/reply?quote=5092019

He says using linear space and CaptureFromTexture with R16G16B16A16_SFLOAT causes the capture to be too dark.

He also said then using CaptureFromScreen but that didn't capture correctly...

Unity version 2019.2
Not sure which version of MovieCapture, but it's the trial version

**Comment by AndrewRH** [comment]
Hey @MorrisRH I've added a test scene for this TestLinearTextureCapture.
It seems there may be an issue on Windows as well....

With Unity set to High Quality and Linear colourspace, it should look like this:
![image](https://user-images.githubusercontent.com/5418126/73665074-67488280-4698-11ea-9583-85654d6fa7d0.png)

But the capture I get looks like this:
![image](https://user-images.githubusercontent.com/5418126/73665320-cd350a00-4698-11ea-9f77-794802f201c7.png)


So I think I've reproduced the bug....

**Comment by AndrewRH** [comment]
Closing this issue as it's fixed in 4.0.3

**Comment by kidapu** [comment]
@AndrewRH 
I'm in trouble with this issue.
When will you plan to release version 4.0.3 in Unity Asset Store?

**Comment by BirdInTheCity** [comment]
I downloaded the v4.0.3 demo and I'm still seeing this bug.  I've posted about it on the [Unity Forum](https://forum.unity.com/threads/released-avpro-movie-capture.120717/page-19#post-5493979).  

Visual reference of the bug:
![output-sample](https://user-images.githubusercontent.com/814522/74781562-e9bb6f80-525e-11ea-856e-bc57fc78b69a.png)

**Comment by kidapu** [comment]
@AndrewRH @BirdInTheCity 
I also still encounter this bug. 

My enviroment is below.

- AVPro 4.0.3
- iOS 13.2 +  iPhone 8
- Unity 2019.2.14f1
- Player Settings -> Other Settings -> Color Space : Linear

<img width="600" alt="Screen_Shot_2020-02-19_at_8_59_22" src="https://user-images.githubusercontent.com/720154/74788984-b0364300-52f6-11ea-87b9-1ba760cadd87.png">

**Comment by AndrewRH** [comment]
@BirdInTheCity  are you using CaptureFromScreen or CaptureFromCamera or something else?

**Comment by AndrewRH** [comment]
@kidapu is that from CaptureFromCamera component?  Or perhaps you're using something else like the AVPro Movie Capture Window?  We're going to try to fix this today but we need to be able to replicate the bug first....

Thanks for your patience :)

**Comment by kidapu** [comment]
@AndrewRH I use CaptureFromCamera. I will upload my simple test code without `Plugins` dir later.

**Comment by AndrewRH** [comment]
> @AndrewRH I' m using `CaptureFromCamera`. I will upload my simple test code without `Plugins` dir later for reproducing the bug.

Thanks that would be great!   If you could share it here, or even email directly to unitysupport@renderheads.com

**Comment by kidapu** [comment]
@AndrewRH 
I uploaded my simple test code.
https://github.com/kidapu/AVProMovieCaptureUnitTest

The script for starting rec is below. 
https://github.com/kidapu/AVProMovieCaptureUnitTest/blob/master/Assets/Scripts/MainController.cs

And I got a recorded movie file from iPhone directly with  using Xcode -> Window ->  Devices and Simulators.

**Comment by AndrewRH** [comment]
> @AndrewRH
> I uploaded my simple test code.
> https://github.com/kidapu/AVProMovieCaptureUnitTest
> 
> The script for starting rec is below.
> https://github.com/kidapu/AVProMovieCaptureUnitTest/blob/master/Assets/Scripts/MainController.cs
> 
> And I got a recorded movie file from iPhone directly with using Xcode -> Window -> Devices and Simulators.

Thanks for this, we're testing it now

**Comment by AndrewRH** [comment]
@kidapu  and in your project, if you capture in the Unity editor - then is it fine?  It's only when you do a capture on iOS device that you have this darkening problem?

**Comment by kidapu** [comment]
@AndrewRH YES, Exactly!

**Comment by AndrewRH** [comment]
@kidapu we ran your scene on iOS device and captured....and the capture looks fine for us.  We didn't see any darkening....  I'm not sure why you're seeing something different.  

1) Are you using the trial or the full version of the plugin?
2) Could you try reimporting the 4.0.3 plugin again and try it?  When you do this, please first close Unity, then open it and do the plugin reimport.
3) Could you show us a screenshot / video of your capture?

Thanks,

**Comment by kidapu** [comment]
@AndrewRH 
Mmm...

> 1

I'm using the full version.

> 2

I have done this. But I can't resolve my issue.

> 3
The below link has a video of my capture on my iPhone.
This link will expire after 6 days.

https://www.dropbox.com/transfer/AAAAAF5R2ECoLwJzEyHo-UPvoVe2aSt1dzvlDHI8tU9593aVfE6cDhA

**Comment by kidapu** [comment]
@AndrewRH 
What's your test environment? (Version of unity, iOS, iPhone...etc )

**Comment by AndrewRH** [comment]
> @AndrewRH
> What's your test environment? (Version of unity, iOS, iPhone...etc )

Wow yes your video is very dark...we don't get that here.
Our test environment is slightly different:
iPad Pro 10.5", iOS 13.3.1....
XCode 11.3.1 macOS Catalina 10.15.3

We have an iPhone X here, also with 13.3.1  - we'll test on this next

**Comment by kidapu** [comment]
@AndrewRH 
Thanks. I will also test on another version of the iPhone device. 

I have one more question.

Did you set the color space as `Linear` in  Unity Project Settings?
<img width="669" alt="Screen_Shot_2020-02-19_at_22_26_28" src="https://user-images.githubusercontent.com/720154/74838673-54f06900-5367-11ea-8703-25e49b9aceec.png">

If it's set `Gamma`, I can record videos successfully.

**Comment by AndrewRH** [comment]
@kidapu Yes we are definitely using Linear.... We will keep testing on our side...
Do let us know if you find any other clues.

**Comment by AndrewRH** [comment]
@kidapu We have replicated the bug on the iPhone X.. we're debugging it now and will get back to you....Thanks!

**Comment by kidapu** [comment]
Thanks for your patience!

**Comment by BirdInTheCity** [comment]
Looks like you were able to reproduce while I was asleep! ;)  But here are my specs, in case it's still helpful:

AVPro v4.0.3 Demo 
(Buying the real one, once the expense report gets approved!)
iOS 13.2 + iPhone 11 Pro Max
Unity v2019.3.0f6 for Mac
Player Settings -> Other Settings -> 
Color Space : Linear
Color Gamut: sRGB

The color looks correct in videos created in editor on Desktop (osx) but the exported video appears too dark on builds in iOS.

**Comment by AndrewRH** [comment]
This should be resolved now in the new version 4.0.4 
Please upgrade and let us know :)

Thanks,

**Comment by BirdInTheCity** [comment]
Fixed! Thank you for the quick response on this.

**Comment by kidapu** [comment]
@AndrewRH 
Fixed, too! Thank you for your cooperation and kindness!

**Comment by AndrewRH** [comment]
We are glad to hear that the issue is fixed :)   Thanks @kidapu for all the help!

I will close this issue now.  If anyone still has the issue please create a new issue.
