### ISSUE TITLE
Camera Rotation doesn't work in VRcamera360. mono

### ISSUE THREAD

**Issue by gkdlvjzl** [RenderHeads/UnityPlugin-AVProMovieCapture#294]
**Describe the bug**
Camera Rotation doesn't work in VRcamera360.
Rotation works for stereo rendering(topB/LR), but rotation doesn't work for none.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.17f1
 - AVPro Movie Capture version: desktop edition
 - Operating system version: Window10
 - Capture component used: 360 vr + stereo
 - Capture settings (resolution, frame-rate, codec): 
 - 
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/48200179/d5485195-b78b-4230-9f5b-313a52dc4aff)

**Videos**
[https://drive.google.com/file/d/18C6WL-_IPgSsP_3c5xNCPIRKWXKZUZ3B/view?usp=sharing](url)
Mono video with location issues

[https://drive.google.com/file/d/1tOB1VYwiUa7zeQdFrLYQ_U7kof1d2SIX/view?usp=sharing](url)
Stereo with no problems with location

**Comment by Chris-RH** [comment]
hmmm, I see what you mean.
Are you able to send us a minimal project that reproduces the issue please? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by gkdlvjzl** [comment]
https://drive.google.com/file/d/1mo0xmwAxs0LreXTbOmWQZxPT_maRHLOT/view?usp=sharing
Here is my project link.
It took time to reduce the capacity by deleting assets.
In the process of deleting, the project may be strange.
This is the result of an effort to reduce it as much as possible.
Is it a problem that occurs during the process of merging into children in
the timeline after investigating the problem? I have a doubt.

Google translate was used.
We apologize in advance for the inconvenience caused by poor communication
or unintended communication.

**Comment by gkdlvjzl** [comment]
Sent mail. At the moment, I was taken aback by the Google mail reply registered here.

**Comment by gkdlvjzl** [comment]
Problem solved. thank you!
456 line if (>>this<<.transform.rotation == Quaternion.identity)
→
if (>>camera<<.transform.rotation == Quaternion.identity)
DONE

2023년 6월 20일 (화) 오전 2:27, Chris-RH ***@***.***>님이 작성:

**Comment by Chris-RH** [comment]
This has been fixed in the latest release.  Please let us know if it is still an issue after updating.

**Comment by VicEsquivel** [comment]
@Chris-RH The issue is still there, if you select the 180 degree mode. In line 426, it also needs to be changed to `if (camera.transform.rotation == Quaternion.identity)`
